[package]
org = "ecommerce"
name = "ballerina_backend"
version = "0.1.0"
distribution = "2201.10.0"

[dependencies]

[platform.java17.dependency]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.6.0"